# Data Analysis with Python and Pandas


## pandas and NumPy intro

NumPy stands for Numerical Python and forms the foundation of pandas.
pandas DataFrames are built on top of NumPy arrays.

## NumPy arrays and array properties

`np` is the standard alias for the NumPy library. Below we create a Python
list and convert it into a NumPy array using the `array` function.

In [213]:
import numpy as np

# To create an array filled with a specific value (e.g., 2 in a 2x5 array):
np.full((2, 5), 2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [46]:
sales_2 = sales / 2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [ ]:
sales_2

In [47]:
import numpy as np

# *
sales = [0, 5, 155, 0, 518, 0, 1827, 616, 317, 325]
sales_array = np.array(sales)
sales_array

array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325])

In [48]:
sales_array * 2


array([   0,   10,  310,    0, 1036,    0, 3654, 1232,  634,  650])

Check the type of the array. It's an `ndarray` (N-dimensional array).

In [49]:
type(sales_array)

numpy.ndarray

Key array attributes: number of dimensions, shape, size, and data type.

In [50]:
sales_array.ndim

1

To check for dimensions...One dimensional; because it is a list, one row and several columns.

In [51]:
sales_array.shape

(10,)

In [52]:
sales_array.size

10

In [53]:
sales_array.dtype

dtype('int64')

To create a two-dimensional array, pass in nested lists of equal length.

In [54]:
# *
sales = [[0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]]
sales_array = np.array(sales)
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [55]:
sales_array.ndim

2

2 lists

In [56]:
sales_array.shape

(2, 5)

In [57]:
sales_array.size

10

In [58]:
sales_array.dtype

dtype('int64')

### Demo: arrays

In Jupyter, typing a package name followed by a dot and pressing Tab shows
all available functions (Tab completion).

In [59]:
import numpy as np

In [60]:
np.array(range(5))

array([0, 1, 2, 3, 4])

In [61]:
array = np.array(range(5))
array

array([0, 1, 2, 3, 4])

Create a two-dimensional array. Each element in the list becomes one
dimension in the 2D array.

In [62]:
array_2d = np.array([range(5), range(5)])
array_2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

With NumPy we no longer need to loop to perform operations. Adding 1 adds
to all numbers across both dimensions.

In [63]:
array_2d + 1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [64]:
array.shape

(5,)

In [65]:
array_2d.shape

(2, 5)

In [66]:
array.size

5

In [67]:
array_2d.shape

(2, 5)

The transpose method (`T`) swaps the axes.

In [68]:
array_2d.T

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [69]:
array_2d.T.shape

(5, 2)

In [70]:
array.ndim

1

In [71]:
array_2d.ndim

2

In [72]:
array.dtype

dtype('int64')

In [73]:
array_2d.dtype

dtype('int64')

Data type for a non-integer array. `U6` means a Unicode string with a
maximum length of six.

In [74]:
# *
array = np.array(["I", "love", "Python"])
array.dtype

dtype('<U6')

## Challenge: Array basics

Convert a list into a NumPy array and report its properties.

## Solution: Array basics

In [75]:
import numpy as np

In [76]:
# *
my_list = [x for x in range(10, 101, 10)]

In [77]:
my_array = np.array(my_list)
my_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [78]:
my_array.ndim

1

In [79]:
my_array.shape

(10,)

In [80]:
my_array.size

10

In [81]:
my_array.dtype

dtype('int64')

Previewing the reshape method to see how dimensions change.

In [82]:
my_array.reshape(1, 10)

array([[ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [83]:
my_array.reshape(10, 1)

array([[ 10],
       [ 20],
       [ 30],
       [ 40],
       [ 50],
       [ 60],
       [ 70],
       [ 80],
       [ 90],
       [100]])

In [84]:
my_array.reshape(2, 5)

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [85]:
my_array.reshape(5, 2)

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

## Array creation

Useful functions to create arrays from scratch as an alternative to
converting base Python data types.

The `ones` function creates an array of ones with the given dimensions
(stored as floats by default).

In [86]:
np.ones((10, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [207]:
np.ones((10, 2), int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

The `zeros` function creates an array of zeros. Here we specify two rows,
five columns, and an integer data type.

In [87]:
np.zeros((2, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

`arange` is analogous to base Python's `range` but automatically creates a
NumPy array.

In [218]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [219]:
Range= range(10)

In [210]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`linspace` creates an array of evenly spaced floats given a start, stop
(inclusive), and number of elements.

In [240]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [231]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

The `reshape` method changes an array into compatible dimensions.

In [90]:
np.arange(1, 8, 2).reshape(2, 2)

array([[1, 3],
       [5, 7]])

### Demo: array creation

In [91]:
import numpy as np

In [238]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [237]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [235]:
np.ones(2, int)

array([1, 1])

In [94]:
np.ones(2, dtype=int)

array([1, 1])

In [95]:
np.zeros(100, "int").reshape(10, 10)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [96]:
np.zeros((5, 20), "int")

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

NumPy also has linear algebra functionality, such as the identity matrix.

In [97]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [98]:
np.identity(10).T

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [99]:
np.zeros((5, 20)).T

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [100]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [102]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

`linspace`: note you need n+1 points when including 0 to get the multiples
you expect.

In [103]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [104]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [105]:
np.linspace(8, 64, 8)

array([ 8., 16., 24., 32., 40., 48., 56., 64.])

In [106]:
np.linspace(0, 64, 9)

array([ 0.,  8., 16., 24., 32., 40., 48., 56., 64.])

## Random number generation

Create a random number generator with a seed so results are reproducible
across sessions. `rng` is the standard variable name.

In [107]:
from numpy.random import default_rng

rng = default_rng(12345)
random_array = rng.random(10)
random_array

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

Drawing from a normal distribution with a given mean and standard deviation.

In [108]:
rng = default_rng()
mean = 5
std = 1
rng.normal(mean, std, 10)

array([4.28281113, 4.07058476, 4.44571947, 5.7278743 , 4.94258794,
       5.59032706, 6.10749979, 3.76442533, 5.65253993, 7.3178064 ])

### Demo: random number generation

In [109]:
import numpy as np

In [110]:
rng = np.random.default_rng(616)
rng.random(10)

array([0.39682145, 0.86568572, 0.46040359, 0.30599848, 0.57381588,
       0.08888468, 0.88194347, 0.73228387, 0.73215182, 0.56233394])

In [111]:
rng.random(5)

array([0.33966929, 0.062511  , 0.35706816, 0.20250319, 0.4305179 ])

In [112]:
rng.random(100)

array([0.1033163 , 0.52396562, 0.80203893, 0.07529808, 0.15143375,
       0.89684192, 0.66336909, 0.72612724, 0.76560278, 0.02961401,
       0.77821778, 0.96179431, 0.18988288, 0.16903606, 0.47431033,
       0.59182385, 0.42537177, 0.82177265, 0.38023964, 0.02154055,
       0.98150375, 0.54986705, 0.50866454, 0.22631697, 0.01686436,
       0.8520208 , 0.89723864, 0.80578865, 0.90879236, 0.37141849,
       0.41116148, 0.29953469, 0.35593281, 0.37394491, 0.03692463,
       0.43744429, 0.57010814, 0.19746347, 0.28743367, 0.77594544,
       0.22445369, 0.49109205, 0.63450957, 0.34689249, 0.50827751,
       0.80364437, 0.55857875, 0.54981699, 0.93059545, 0.11717621,
       0.695153  , 0.47241633, 0.53068063, 0.29480844, 0.30735776,
       0.93511134, 0.07721433, 0.35905049, 0.72180595, 0.39022153,
       0.22152597, 0.48662891, 0.76138129, 0.16711022, 0.64324466,
       0.26020707, 0.71974437, 0.69220868, 0.38767211, 0.07808919,
       0.26657983, 0.88703137, 0.02319653, 0.52328187, 0.62951

In [113]:
rng.random(10)

array([0.24020696, 0.86688038, 0.69816215, 0.49251625, 0.02652721,
       0.11815832, 0.8111401 , 0.20895342, 0.56053694, 0.66275723])

Generating random integers between a start and end point.

In [114]:
rng.integers(0, 10, 100)

array([9, 8, 3, 9, 7, 1, 7, 9, 6, 4, 6, 0, 9, 8, 1, 2, 5, 5, 9, 8, 3, 0,
       9, 8, 3, 7, 5, 6, 4, 8, 0, 8, 0, 4, 9, 0, 7, 7, 0, 7, 1, 5, 7, 7,
       7, 8, 3, 7, 3, 8, 5, 7, 3, 1, 4, 7, 6, 7, 5, 9, 5, 0, 9, 1, 5, 9,
       5, 8, 6, 4, 6, 7, 9, 2, 2, 6, 4, 0, 2, 8, 1, 9, 8, 6, 5, 0, 6, 0,
       3, 8, 7, 6, 5, 8, 8, 4, 2, 8, 5, 6])

Drawing from a normal distribution centered around 50 with a standard
deviation of 5.

In [115]:
rng.normal(50, 5, 10)

array([47.45287589, 52.51216663, 45.73565211, 44.56405959, 41.77643396,
       48.99174891, 50.27080975, 45.69987367, 53.76265684, 55.55436222])

## Challenge: Array creation

Recreate the array of multiples of 10 (10 to 100) as 5 rows by 2 columns,
then create a 3x3 array of random numbers between 0 and 1.

## Solution: Array creation

In [116]:
my_array = np.linspace(10, 100, 10)

In [117]:
my_array

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [118]:
my_array.reshape(5, 2)

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

Alternative approaches using `arange`.

In [119]:
np.arange(10, 101, 10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [120]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [121]:
np.arange(1, 11) * 10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [122]:
(np.arange(1, 11) * 10).reshape(5, 2)

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

Creating a 3x3 array of random numbers with a random state of 2022.

In [123]:
rng = np.random.default_rng(2022)
random_array = rng.random(9).reshape(3, 3)
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

We can also pass the dimensions directly into the random method.

In [124]:
rng.random((3, 3))

array([[0.98862926, 0.96919869, 0.25697153],
       [0.55876211, 0.24234798, 0.32202029],
       [0.89135975, 0.94611366, 0.72253931]])

## Indexing and slicing arrays

Access elements by indexing (single element) or slicing (a series of
elements). Python is zero-indexed and stop points are not inclusive.

In [125]:
# *
product_array = np.array(["fruits", "vegetables", "cereal", "dairy", "eggs",
                          "snacks", "beverages", "coffee", "tea", "spices"])

Indexing a one-dimensional array. Index 1 grabs the second element; index
-1 grabs the last element (negative indexing works from the end).

In [126]:
product_array[1]

np.str_('vegetables')

In [127]:
product_array[-1]

np.str_('spices')

Slicing: with no start point it defaults to 0; with no step size it
defaults to 1.

In [128]:
product_array[:5]

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'], dtype='<U10')

In [129]:
product_array[5::2]

array(['snacks', 'coffee', 'spices'], dtype='<U10')

In [130]:
# *
product_array2D = product_array.reshape(2, 5)

Slicing a two-dimensional array requires coordinates: row then column.
Coffee is in the second row (index 1), third column (index 2).

In [131]:
product_array2D[1, 2]

np.str_('coffee')

Grab all rows, but slice columns from the third column to the end.

In [132]:
product_array2D[:, 2:]

array([['cereal', 'dairy', 'eggs'],
       ['coffee', 'tea', 'spices']], dtype='<U10')

Grab all columns, but only the second row onward.

In [133]:
product_array2D[1:, :]

array([['snacks', 'beverages', 'coffee', 'tea', 'spices']], dtype='<U10')

### Demo: indexing and slicing

In [134]:
import numpy as np

In [135]:
integer_array = np.arange(12)
integer_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [136]:
integer_array[0]

np.int64(0)

In [137]:
integer_array[1]

np.int64(1)

In [138]:
integer_array[2]

np.int64(2)

In [139]:
integer_array[11]

np.int64(11)

In [140]:
integer_array[-1]

np.int64(11)

In [141]:
integer_array[-2]

np.int64(10)

Slicing the one-dimensional array.

In [142]:
integer_array[:5]

array([0, 1, 2, 3, 4])

In [143]:
integer_array[5:]

array([ 5,  6,  7,  8,  9, 10, 11])

In [144]:
integer_array[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [145]:
integer_array[::2]

array([ 0,  2,  4,  6,  8, 10])

Reshape into a 3x4 array and practice slicing in two dimensions.

In [146]:
new_array = integer_array.reshape(3, 4)
new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [147]:
new_array[:, :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [148]:
new_array[1:, :]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [149]:
new_array[:, 3]

array([ 3,  7, 11])

In [150]:
new_array[:, 1:]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

Grab a single coordinate: the number 9 is at row index 2, column index 1.

In [151]:
new_array[2, 1]

np.int64(9)

## Challenge: Indexing and slicing arrays

Starting with the random array created earlier, grab the first two rows,
the first column, and the second number in the third row.

## Solution: Indexing and slicing arrays

Grab the first two rows. The first portion of indexing accesses rows, so a
single argument with a stop point of 2 returns rows at index 0 and 1
(stop point is not inclusive).

In [152]:
random_array[:2]

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778]])

Optionally add a column component. A colon grabs all columns.

In [153]:
random_array[:2, :]

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778]])

Grab the entire first column: all rows, column index 0.

In [154]:
random_array[:, 0]

array([0.24742606, 0.06066207, 0.1108689 ])

Grab the second element of the third row: row index 2, column index 1.

In [155]:
random_array[2, 1]

np.float64(0.04305584439252108)

## Array operations

Python's arithmetic operators can be used to perform array operations. With
NumPy there is no need to loop; the operation is applied element wise. The
concepts that make this work are vectorisation and broadcasting, which
eliminate the need for explicit loops in our code.

Add a scalar to every value in the array (for example, a tax or shipping
cost). NumPy broadcasts the 2 across every element.

In [156]:
# *
sales = [[0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]]
sales_array = np.array(sales)
sales_array + 2

array([[   2,    7,  157,    2,  520],
       [   2, 1829,  618,  319,  327]])

Multiply two arrays of the same length element wise. Here we slice the first
row into quantity and the second row into price, then multiply.

In [157]:
quantity = sales_array[0]
price = sales_array[1]
quantity * price

array([     0,   9135,  95480,      0, 168350])

### Demo: array operations

In [158]:
import numpy as np

In [159]:
rng = np.random.default_rng(616)
inventory = rng.integers(0, 100, 10)
inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57])

Apply a uniform transformation to the series by subtracting a scalar. Note
that some values may become negative.

In [160]:
inventory - 24

array([ 15,  15,  69,  62,  24,  22,  24,   6, -13,  33])

Division casts the result to floats, because there is usually a remainder.

In [161]:
inventory / 2

array([19.5, 19.5, 46.5, 43. , 24. , 23. , 24. , 15. ,  5.5, 28.5])

Operations between arrays require matching lengths. Here we create a price
array of 10 random numbers and round to two decimal places.

In [162]:
price = rng.random(10) * 10
price = price.round(2)
price

array([0.89, 8.82, 7.32, 7.32, 5.62, 3.4 , 0.63, 3.57, 2.03, 4.31])

Multiplying the two arrays element wise gives the total value of each item,
and the sum method gives the total inventory value.

In [163]:
price * inventory

array([ 34.71, 343.98, 680.76, 629.52, 269.76, 156.4 ,  30.24, 107.1 ,
        22.33, 245.67])

In [164]:
(price * inventory).sum()

np.float64(2520.4700000000003)

## Challenge: Array operations

Add a flat shipping cost of five to the prices to get the total amount owed.
The numbers in the random array represent a discount percent, so subtract the
first six numbers in the random array from one to get the percent owed, then
multiply percent owed by total to get the final amount owed.

## Solution: Array operations

In [165]:
# *
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

Add a shipping cost of five to every price.

In [166]:
total = prices + 5
total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

Grab the first six numbers from the random array by slicing the first two
rows and reshaping to a one-dimensional array of six elements.

In [167]:
discount_percent = random_array[:2, :].reshape(6)
discount_percent

array([0.24742606, 0.09299006, 0.61176337, 0.06066207, 0.66103343,
       0.75515778])

Subtract the discount percent from one to get the percent owed. A 25% discount
means paying 75% of the price.

In [168]:
percent_owed = 1 - discount_percent
percent_owed

array([0.75257394, 0.90700994, 0.38823663, 0.93933793, 0.33896657,
       0.24484222])

Multiply total by percent owed to get the final amount owed, rounded to two
decimal places.

In [169]:
final_owed = (total * percent_owed).round(2)
final_owed

array([ 8.27, 10.88, 10.67, 98.62,  3.39, 13.46])

These steps can be combined into a single expression, though step by step is
clearer to read.

In [170]:
((1 - random_array[:2, :].reshape(6)) * total).round(2)

array([ 8.27, 10.88, 10.67, 98.62,  3.39, 13.46])

## Filtering arrays and modifying array values

We can filter arrays by indexing them with a logical test. Only the elements
at positions where the test returns True are returned in the resulting array.

A logical test on an array returns a Boolean array of True and False values.

In [171]:
# *
sales_array = np.array([0, 5, 155, 0, 518, 0, 1827, 616, 317, 325])
sales_array != 0

array([False,  True,  True, False,  True, False,  True,  True,  True,
        True])

Passing the Boolean array back into the index filters out the values where the
test returned False (here, the zeros).

In [172]:
sales_array[sales_array != 0]

array([   5,  155,  518, 1827,  616,  317,  325])

Combine logical tests with the pipe operator for or and the ampersand for and.
Unlike base Python, the words and and or cannot be used. Each condition must be
wrapped in parentheses.

In [173]:
sales_array[(sales_array == 616) | (sales_array < 100)]

array([  0,   5,   0,   0, 616])

An and condition mimics a between operator. Here we grab sales between 100 and
500, not inclusive.

In [174]:
sales_array[(sales_array > 100) & (sales_array < 500)]

array([155, 317, 325])

Complex conditions can be stored in a variable, often called a mask, to keep
the filter readable.

In [175]:
mask = (sales_array > 100) & (sales_array < 500)
sales_array[mask]

array([155, 317, 325])

We can filter one array by the values in another array of identical length.
Here we return products where sales were greater than zero.

In [176]:
# *
sales_array = np.array([0, 5, 155, 0, 518])
product_array = np.array(["fruits", "vegetables", "cereal", "dairy", "eggs"])
product_array[sales_array > 0]

array(['vegetables', 'cereal', 'eggs'], dtype='<U10')

Modifying array values. To assign a new value, specify the index and assign in
the new value.

In [177]:
# *
sales_array = np.array([0, 5, 155, 0, 518, 0, 1827, 616, 317, 325])
sales_array[1] = 25
sales_array

array([   0,   25,  155,    0,  518,    0, 1827,  616,  317,  325])

Filtering can also be used to change a set of values that meet a logical
criterion. Here any value equal to zero is changed to five.

In [178]:
sales_array[sales_array == 0] = 5
sales_array

array([   5,   25,  155,    5,  518,    5, 1827,  616,  317,  325])

### Demo: filtering and modifying

In [179]:
import numpy as np

In [180]:
my_array = np.arange(20)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

A logical test for even numbers using the modulo operator: the remainder of
division by two is zero.

In [181]:
my_array % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

Filter the array down to only the even numbers.

In [182]:
my_array[my_array % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

The same logic works on text arrays. Here we build an array alternating even
and odd.

In [183]:
even_odd = np.array(["even", "odd"] * 10)
even_odd

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [184]:
even_odd != "odd"

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [185]:
even_odd[even_odd != "odd"]

array(['even', 'even', 'even', 'even', 'even', 'even', 'even', 'even',
       'even', 'even'], dtype='<U4')

Replace all even numbers in my_array with zero using the text array as a mask.

In [186]:
my_array[even_odd != "odd"] = 0
my_array

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

Change a single element back via indexing.

In [187]:
my_array[2] = 2
my_array

array([ 0,  1,  2,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

Two conditions joined with or. Because every value is either even or odd, this
or condition is always True and nothing is filtered out.

In [188]:
mask = (even_odd != "odd") | (even_odd != "even")
even_odd[mask]

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

An and condition returns an empty array, because no value is both even and odd.

In [189]:
mask = (even_odd != "odd") & (even_odd != "even")
even_odd[mask]

array([], dtype='<U4')

## The where() function

The where function performs a logical test and returns one value where the test
is True and another where it is False. Syntax: `np.where(test, value_if_true,
value_if_false)`.

In [190]:
# *
inventory_array = np.array([10, 25, 5, 0, 0])
product_array = np.array(["fruits", "vegetables", "cereal", "dairy", "eggs"])

If inventory is less than or equal to zero, return "out of stock", otherwise
"in stock".

In [191]:
np.where(inventory_array <= 0, "out of stock", "in stock")

array(['in stock', 'in stock', 'in stock', 'out of stock', 'out of stock'],
      dtype='<U12')

The false value can pull from another array. Here we return the product name
where stock exists, and "out of stock" otherwise.

In [192]:
np.where(inventory_array <= 0, "out of stock", product_array)

array(['fruits', 'vegetables', 'cereal', 'out of stock', 'out of stock'],
      dtype='<U12')

### Demo: where()

In [193]:
import numpy as np

In [194]:
my_array = np.arange(20)

Recreate the even/odd logic using where.

In [195]:
np.where(my_array % 2 == 0, "even", "odd")

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

where can be chained. Even numbers stay "even"; odd numbers are checked again,
and the value nine is pulled from the array while the rest become "odd".

In [196]:
np.where(my_array % 2 == 0, "even", np.where(my_array == 9, my_array, "odd"))

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       '9', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U21')

## Challenge: Filtering and modifying arrays

Filter the product list to those with prices greater than 25. Then modify the
logic to force cola into the list, calling this array fancy_feast_special.
Finally, create a shipping cost array where shipping is zero if price is greater
than 20, otherwise five.

## Solution: Filtering and modifying arrays

In [197]:
# *
products = np.array(["salad", "bread", "mustard", "rare tomato", "cola",
                     "gourmet ice cream"])
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

Filter products to those with a price greater than 25.

In [198]:
products[prices > 25]

array(['rare tomato', 'gourmet ice cream'], dtype='<U17')

Add a second condition with the or operator to force cola into the list, using
a mask to keep the filter readable.

In [199]:
mask = (prices > 25) | (products == "cola")
fancy_feast_special = products[mask]
fancy_feast_special

array(['rare tomato', 'cola', 'gourmet ice cream'], dtype='<U17')

Create a shipping cost array: zero if price is greater than 20, otherwise five.

In [200]:
shipping = np.where(prices > 20, 0, 5)
shipping

array([5, 5, 0, 0, 5, 0])